import {
  CircleHelp,
  MapPin,
  ArrowUp,
  CornerUpLeft,
  CornerUpRight,
  ArrowLeft,
  ArrowRight,
  ChevronsLeft,
  ChevronsRight,
  RotateCcw,
  Anchor,
  RefreshCcw,
  GitMerge,
  LogOut,
  Shuffle,
  GitBranch,
  GitBranchPlus,
  Play,
  ListOrdered,
  Ship,
  CornerDownRight,
  CornerDownLeft,
} from 'lucide-react';

export const maneuverIcons: Record<string, React.ElementType> = {
  esriDMTUnknown: CircleHelp,
  esriDMTStop: MapPin,
  esriDMTStraight: ArrowUp,
  esriDMTBearLeft: CornerUpLeft,
  esriDMTBearRight: CornerUpRight,
  esriDMTTurnLeft: ArrowLeft,
  esriDMTTurnRight: ArrowRight,
  esriDMTSharpLeft: ChevronsLeft,
  esriDMTSharpRight: ChevronsRight,
  esriDMTUTurn: RotateCcw,
  esriDMTFerry: Anchor,
  esriDMTRoundabout: RefreshCcw,
  esriDMTHighwayMerge: GitMerge,
  esriDMTHighwayExit: LogOut,
  esriDMTHighwayChange: Shuffle,
  esriDMTForkCenter: GitBranch,
  esriDMTForkLeft: GitBranchPlus,
  esriDMTForkRight: GitBranchPlus,
  esriDMTDepart: Play,
  esriDMTTripItem: ListOrdered,
  esriDMTEndOfFerry: Ship,
  esriDMTRampRight: CornerDownRight,
  esriDMTRampLeft: CornerDownLeft,
};
